create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');

-- create type status as enum ('active', 'deleted');
-- create table contact
-- (
--     id    bigint generated by default as identity,
--     last_name    varchar(200) not null,
--     first_name    varchar(200) not null,
--     email    varchar(200) not null,
--     phone_number    varchar(200) not null,
--     company_id    bigint,
--     comment    varchar(200) not null,
--     status    status,
--     create_time    timestamp,
--     update_time    timestamp,
--     constraint pk_contact primary key (id),
--     constraint fk_company foreign key (company_id) references company (id)
-- );
